# Generated by Django 4.1.4 on 2024-03-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_status', models.BooleanField(default='True')),
                ('rollno', models.IntegerField()),
                ('grade', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=100)),
                ('urdu', models.CharField(max_length=100)),
                ('sst', models.CharField(max_length=100)),
                ('math', models.CharField(max_length=100)),
                ('science', models.CharField(max_length=100)),
                ('computer', models.CharField(max_length=100)),
                ('islamiyat', models.CharField(max_length=100)),
                ('kashmiri', models.CharField(max_length=100)),
            ],
        ),
    ]
