# Generated by Django 4.1.4 on 2023-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('urdu', models.CharField(max_length=50)),
                ('sst', models.CharField(max_length=50)),
                ('math', models.CharField(max_length=50)),
                ('science', models.CharField(max_length=50)),
                ('computer', models.CharField(max_length=50)),
                ('islamiyat', models.CharField(max_length=50)),
                ('kashmiri', models.CharField(max_length=50)),
                ('conduct', models.CharField(max_length=50)),
            ],
        ),
    ]
