# Generated by Django 4.1.4 on 2023-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('notice', models.CharField(max_length=500)),
            ],
        ),
    ]
