# Generated by Django 4.1.4 on 2024-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='caption',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='programs',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
