# Generated by Django 4.1.4 on 2024-02-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programs_caption_alter_programs_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='image',
            field=models.ImageField(default=1, upload_to='capion_image/'),
            preserve_default=False,
        ),
    ]
