# Generated by Django 4.1.4 on 2024-02-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='image',
        ),
    ]
